### ISSUE TITLE
Error when Creating Database

### ISSUE THREAD

**Issue by saatviks** [bloomberg/comdb2#549]
I'm using MacOS High Sierra 10.13.1 and am able to build and install ComDB2.
I started the pmux service(`pmux -n`) and added my hostname in `/opt/bb/etc/cdb2/config/comdb2.d`. 
Now when I run the command to create the database: `comdb2 --create --dir ~/db testdb`, I'm getting the following error log.
```
resolve_dc(Saatviks-MBP.wv.cc.cmu.edu) open rc -1 cdb2_get_dbhosts: no default_type entry in comdb2db config.!
machine_class_default(Saatviks-MBP.wv.cc.cmu.edu) open rc -1 cdb2_get_dbhosts: no default_type entry in comdb2db config.!
ASYNCHRONOUS MODE
LOG DELETE ENABLED
LOG DELETE POLICY: delete all eligible log files
NEW MASTER NODE fakehost
[ERROR] Failed to open low level meta table, rc: 2
[FATAL] Failed to open low level meta table, rc: 0
[FATAL] failed to start
```

**Comment by riverszhang89** [comment]
I am not able to reproduce it on Linux. @akshatsikarwar Mind taking a look?

**Comment by akshatsikarwar** [comment]
Thank you for reporting.

Did you change `CMAKE_INSTALL_PREFIX` or `COMDB2_ROOT` during build/install? Did you run `make install` or build tarball and installed binaries from it?

Does it work if you let it create under default location? Try: `comdb2 testdb --create`
Should create under `/opt/bb/var/cdb2/testdb`.

**Comment by akshatsikarwar** [comment]
Saatvik: Can you `dtrace` your original run and post the output? Would like to see whats failing.

**Comment by saatviks** [comment]
I've been following the installation instructions in the README, so I havent added any `CMAKE_INSTALL_PREFIX` or `COMDB2_ROOT`.
While attempting to debug the issue, I tried `sudo USER=${whoami} make install` to solve some permission problems I was getting earlier.
I think `dtrace` is disabled on MacOS Sierra by default as indicated [here](http://blog.shalman.org/enabling-dtrace-on-macos-sierra/). Will follow the instructions to enable and post a trace ASAP.

**Comment by akshatsikarwar** [comment]
Thanks - with default `make install`, you would need write permission at `/opt/bb`. When installing from rpm/deb, a `comdb2` user is created and gets ownership of all the required directories for datafiles and logs.

I'd still like to know why `--dir` didn't work, so the trace output will help.

**Comment by akshatsikarwar** [comment]
You could configure using following, so all binaries and dbs will get installed in `$HOME/comdb2`:
`cmake -DCMAKE_INSTALL_PREFIX=$HOME/comdb2`
Then, path to binaries: `$HOME/comdb2/bin`
and dbs installed to: `$HOME/comdb2/var/cdb2`

**Comment by saatviks** [comment]
I haven't used `dtrace` before - When running it as `dtrace -c 'comdb2 testdb --create'` it says `no dtrace probes specified`. What would be the correct command to pass?

**Comment by akshatsikarwar** [comment]
Try `dtruss`. Thats a truss like wrapper for dtrace. I want to see which files are getting opened. `iosnoop` would probably work just as well.

I have a feeling Its going to be a permission issue somewhere ..

**Comment by saatviks** [comment]
Here's the trace I'm getting:
[op.txt](https://github.com/bloomberg/comdb2/files/1507816/op.txt)

**Comment by riverszhang89** [comment]
```
write_nocancel(0x3, "11/27/17 17:25:13:open_dbs: cannot open XXX.comdb2_llmeta.dta: 22 Invalid argument\n\0", 0x53)		 = 83 0
```

My guess is that `O_DIRECT` isn't supported on macOS.

Could you please add the line below to `$HOME/comdb2/etc/cdb2/config/comdb2.lrl`, and try creating a database again?

```
# To disable direct IO
setattr directio 0
```

**Comment by saatviks** [comment]
I did so, its still failing.

**Comment by akshatsikarwar** [comment]
I can reproduce this. It’s some recent check in. Will git bisect

**Comment by akshatsikarwar** [comment]
:(

8fe2f9ad72bd42eb96334580a31039a883948bd2 is the first bad commit
commit 8fe2f9ad72bd42eb96334580a31039a883948bd2
Author: Akshat Sikarwar <asikarwar1@bloomberg.net>
Date:   Mon Nov 13 13:11:10 2017 -0500

    perfect ✓• not enabled by default

**Comment by akshatsikarwar** [comment]
Will dig in tomorrow..

**Comment by akshatsikarwar** [comment]
@saatviks: Please pull latest master. I've reverted above commit.. it should work now.

**Comment by saatviks** [comment]
Thanks Akshat - Will set it up ASAP and confirm that its working now.

**Comment by saatviks** [comment]
Thanks a lot! Yes its working now. One thing though:
I'm still getting this log which might be problematic?
```
resolve_dc(Saatviks-MBP.wv.cc.cmu.edu) open rc -1 cdb2_get_dbhosts: no default_type entry in comdb2db config.!
machine_class_default(Saatviks-MBP.wv.cc.cmu.edu) open rc -1 cdb2_get_dbhosts: no default_type entry in comdb2db config.!
```
Also should I still need to add the `O_DIRECT` config suggested above?
And if I plan on tinkering with ComDB2 on a single node/locally - do I need to run the `pmux` service?

**Comment by akshatsikarwar** [comment]
You can ignore `resolve_dc`.

**Comment by akshatsikarwar** [comment]
You need to run `pmux`.

**Comment by saatviks** [comment]
Thanks - closing this issue.

**Comment by akshatsikarwar** [comment]
Still need to fix.

**Comment by saatviks** [comment]
Also even though I'm able to run `comdb2 --create testdb  &` and `comdb2 testdb &` successfully, `cdb2sql testdb 'select 1+1 as "math"'` is throwing the following error log:
```
cdb2_tcpresolve:gethostbyname(Saatviks-MacBook-Pro.local): errno=0 err=Undefined error: 0
cdb2_tcpresolve:gethostbyname(Saatviks-MacBook-Pro.local): errno=0 err=Undefined error: 0
cdb2_tcpresolve:gethostbyname(Saatviks-MacBook-Pro.local): errno=0 err=Undefined error: 0
[select 1+1 as "math"] failed with rc -1 cdb2_run_statement_typed_int: Cannot connect to db
```
I'm following the docs from [here](https://bloomberg.github.io/comdb2/example_db.html)

**Comment by riverszhang89** [comment]
Is `Saatviks-MacBook-Pro.local` what you have put in `/opt/bb/etc/cdb2/config/comdb2.d/hostname.lrl`?
Looks like the hostname `Saatviks-MacBook-Pro.local` isn't resolvable.
Could you please remove the hostname file, bounce the database, and try the query again?

**Comment by saatviks** [comment]
I didn't have the `hostname.lrl` file - I didn't recreate it when installing at `$HOME/comdb2`.

**Comment by saatviks** [comment]
Never mind - I deleted the database and ran the steps again - and now its working.

**Comment by riverszhang89** [comment]
Great! In case it happens again, you could use `cdb2sql --host localhost`.
